### ISSUE TITLE
pumpkinsfresno.com and pumpkinkingwholesale.com

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#1]
take screenshots of all the pages on the current client's live site (use a screen capture software that captures the FULL LENGTH of the page; dont waste time screenshotting a section at a time and then combining them in photoshop)

download their entire site as well ( @AaronAguilar can show you how to do this )

upload everything to the appropriate folder in google drive

pumpkinsfresno.com

http://www.pumpkinkingwholesale.com/

Yes, do it for both sites. For this project we are combining both sites into one.

due date:
7-20-15 5p

**Comment by purplyrocky** [comment]
done
https://drive.google.com/open?id=0B_lfcedxYUvffldINWY3Y0V2YkJtUVZHUmF4c21hTWdQaGxlVVIwTU10djF6N0p6YzhzLTg
