### ISSUE TITLE
The "like us on facebook" section

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#10]
Add the "thumbs up" icon that facebook uses for their like button to the orange "like us" button you have. 

Put the icon after the "like us" text. Let's see how it looks. If you don't like it then comment here. 

Keep the link the same.

due date:
7-31-15   5p

**Comment by jperez4509** [comment]
I like it. I changed the text from all caps to just the first letter to capitalize and it looks good. Done.
