### ISSUE TITLE
Remove musical slideshow

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#11]
Client wants everything that slows the site down removed. (yay!)

So please remove the autoplaying video slideshow

due date:
7-31-15   5p

**Comment by jperez4509** [comment]
For this section. Is there anything replacing the slideshow or am I just removing the slideshow and leaving the background image to still have the clear divider  between the about us section and the group section?

**Comment by rodneystrong** [comment]
Excellent question, glad you brought it up. 

As we discussed, let's replace it the suggestion you made about the blood drive info, and then put the wholesale tabular data into that "wholesale" titled tab in the "Products" section.

**Comment by jperez4509** [comment]
done.
