### ISSUE TITLE
Content for image slides at top

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#12]
Replace the text with the hours of operation and location as follows:

Open yearly Oct 1st - 31st 9a - 9p 7 days a week

100 W. Shaw Avenue 
Fresno, CA 93704
P: (559) 240-5516

Style it as you see fit and if you have trouble fitting it all into the circle, feel free to edit as necessary.

This info replace the text for BOTH slides (i'm sorry for the redundancy, but it's necessary).

due date: 
7-31-15   5p

**Comment by jperez4509** [comment]
Alex. The table for the wholesale menu tab is taking a long time and I am not going to reach this deadline. Can I push this back to a new deadline?

**Comment by jperez4509** [comment]
I will complete this task by noon tomorrow.

**Comment by rodneystrong** [comment]
Perfect, thanks for notifying me. New deadline is totally kosher.

**Comment by jperez4509** [comment]
Done.
