### ISSUE TITLE
Width/height of FB widget

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#15]
Make the width: 500px and the height: 400px 

Here's a link that explains how to do it just in case: https://developers.facebook.com/docs/plugins/page-plugin

Have the text on the left of the widget be vertically centered in accordance to the widget on the right if the offset looks really bad. 

due:
8-3-15   2p

**Comment by jperez4509** [comment]
Done.  However the height of 400px looked really tall so I switched it to 300px and used the smaller header that Facebook offers.
