### ISSUE TITLE
media temple add user as contact *sigh*

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#16]
Assigning to you because you know everything:
https://youtu.be/94-6nIVTx5o

**Comment by irms** [comment]
I used akang@editllc.com and it worked. Maybe you're an FTP user?

**Comment by rodneystrong** [comment]
But I tried akang@editllc.com too!! It was my 3rd attempt on that video I linked  T___T) 

*sigh

Thank for the help
