### ISSUE TITLE
Extract logos

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#2]
![pumpkin-logo](https://cloud.githubusercontent.com/assets/539962/8755088/2a1ab46c-2c7d-11e5-8f62-f8ef463aa224.png)
![pumpkin-truck](https://cloud.githubusercontent.com/assets/539962/8755089/2a201768-2c7d-11e5-8102-47c94cf5edec.jpg)

Pull those two logos and create a PNG from them (no background)

For the logo on the side of the truck, use photoshop to correct the perspective. You may need to use the warp tool..

Upload to drive

due date:
7-22-15  11a

**Comment by AaronAguilar** [comment]
For the logo on the side of the truck, do you want me to include the "BLACKSTONE & SHAW" part as well as the url?

**Comment by rodneystrong** [comment]
Good question. Glad you asked. Definitely no.

**Comment by AaronAguilar** [comment]
Here's the first one --
https://drive.google.com/drive/u/0/folders/0B_lfcedxYUvffldINWY3Y0V2YkJtUVZHUmF4c21hTWdQaGxlVVIwTU10djF6N0p6YzhzLTg

**Comment by AaronAguilar** [comment]
Two new ones --  One silver and one that has colors of the pumpkin

https://drive.google.com/drive/u/0/folders/0B_lfcedxYUvffldINWY3Y0V2YkJtUVZHUmF4c21hTWdQaGxlVVIwTU10djF6N0p6YzhzLTg

**Comment by rodneystrong** [comment]
@AaronAguilar Not bad! But you're overdoing it with the gradients. 

Minimize the gradients (think about the radial gradient on the "knot away" logo I had you redo) 

Can you tell me why you chose to have the gradient go from orange to black and yellow to black? 

Also, try 2 more fonts please. Go for a more playful/folksy feel. Don't go as far as the "Lobster" font, but towards there.

**Comment by AaronAguilar** [comment]
I added a new one with a slight gradient of orange to black.  I noticed that they like to stick with the green and tan color so I'll try and play around with green and orange colors. 

I choose that gradient because I wanted to repeat a similar pattern as the pumpkin and how it started from a yellow crown to orange with black as the face features.

**Comment by AaronAguilar** [comment]
Uploaded another one that focuses more on the P and K in the name.

**Comment by AaronAguilar** [comment]
Uploaded two more with two new pumpkins

**Comment by rodneystrong** [comment]
@AaronAguilar 

when you have a moment, let's have a group discussion about these logos and you can tell us why you like them.
