### ISSUE TITLE
Change bg color of tabs

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#3]
![tab](https://cloud.githubusercontent.com/assets/539962/8920659/c69e4ba4-3480-11e5-8069-6ba2aa105b6f.jpg)

Let's try this since the tabs aren't noticeable right away:

make the bg color of the selected tab orange and the text color white.

don't change the bg color of the unselected tabs.

**Comment by jperez4509** [comment]
Done
