### ISSUE TITLE
Add GA tracking code to all pages

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#6]
Copy and paste this right at the bottom before the closing  ```</html>``` tag on every page

<script>

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-65722013-1', 'auto');

ga('send', 'pageview');

</script>

due date:
7-29-15   3p

**Comment by jperez4509** [comment]
You mention to copy and past 'this' at the bottom? But I do not see 'this'?

**Comment by jperez4509** [comment]
Done! Aaron helped me figuring out where the code was at.

**Comment by rodneystrong** [comment]
@jperez4509 sorry about that.. my stupid head forgot to use the correct markdown to not convert it to code  : (
