### ISSUE TITLE
Add google reCapcha code to contact form

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#7]
Step 1: client-side integration

Paste this snippet before the closing </head> tag on your HTML template:
```
<script src='https://www.google.com/recaptcha/api.js'></script>
```
Paste this snippet at the end of the <form> where you want the reCAPTCHA widget to appear:
```
<div class="g-recaptcha" data-sitekey="6LeqegoTAAAAAGiVrFCwCC4KVnABbd9Yn0aEDocv"></div>
```
For an example of this is already done, view the source for this page: http://takobbq.com/catering-contact.html

due date: 
7-29-15    3p

**Comment by jperez4509** [comment]
Where is the snippet with the code? Am I missing something?

**Comment by rodneystrong** [comment]
@jperez4509 ok again sorry about that, i didn't write the correct markdown format to display the code

**Comment by jperez4509** [comment]
Done!
