### ISSUE TITLE
new testimonial

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pumpkin#8]
Please add this to the site. 

Don't use all the text though; I trust your judgement on what part of the testimonial you think would look best for the company.

[Testimonial for Pumpkin Patch.pdf](https://github.com/EditLLC/client-pumpkin/files/1040/Testimonial.for.Pumpkin.Patch.pdf)

due date: 
7-30-15  11p

**Comment by jperez4509** [comment]
Done!
